# 7 数组的基本函数

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [4]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [5]:
np.add(a, a)

array([0, 2, 4, 6])

`argmax()`函数用来返回某个轴上最大值得位置。如果没有定义轴的方向，则数组自动扩展成一维数组，然后返回最大元素的索引值。 

In [6]:
a = np.arange(12).reshape(3, 4)

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.argmax(a, 0)

array([2, 2, 2, 2])

In [9]:
np.argmax(a)

11

**矩阵乘法**：`np.dot`

In [10]:
a = np.arange(12).reshape(3, 4)

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
b = np.arange(12, 24).reshape(4, 3)

In [13]:
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
np.dot(a, b)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# 8 复制和指代

数组的`view()`和切片会返回数组的指代。而`copy`方法会建立一个新的数组对象，和原数组没有任何关系。

# 9 线性代数

Numpy可用于计算矩阵相乘、分解矩阵、求解线性方程等线性问题。

求解矩阵中的逆矩阵 

In [15]:
import numpy.linalg as LA

In [16]:
a = np.arange(1, 10, 1).reshape(3, 3)

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# inva = LA.inv(a)

可以使用solve()函数解决下面这个线性方程组。
```
x1 + 2x2 = 2
2x1 - x2 = 4
```

In [19]:
A = np.array([[1, 2], [2, -1]])

In [20]:
A

array([[ 1,  2],
       [ 2, -1]])

In [21]:
B = np.array([2, 4])

In [22]:
LA.solve(A, B)

array([2., 0.])

使用eig()函数求解一个矩阵的特征值和特征向量。 

In [23]:
q = np.diag((4, 5, 6))

In [24]:
q

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [25]:
x, y = LA.eig(q)

In [26]:
x

array([4., 5., 6.])

In [27]:
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 10 使用数组来处理数据源 

In [28]:
x, y = np.mgrid[0:6*np.pi:0.25, 0:0.4*np.pi:0.25]

In [29]:
x

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.25,  0.25,  0.25,  0.25,  0.25,  0.25],
       [ 0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.5 ],
       [ 0.75,  0.75,  0.75,  0.75,  0.75,  0.75],
       [ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ,  1.  ],
       [ 1.25,  1.25,  1.25,  1.25,  1.25,  1.25],
       [ 1.5 ,  1.5 ,  1.5 ,  1.5 ,  1.5 ,  1.5 ],
       [ 1.75,  1.75,  1.75,  1.75,  1.75,  1.75],
       [ 2.  ,  2.  ,  2.  ,  2.  ,  2.  ,  2.  ],
       [ 2.25,  2.25,  2.25,  2.25,  2.25,  2.25],
       [ 2.5 ,  2.5 ,  2.5 ,  2.5 ,  2.5 ,  2.5 ],
       [ 2.75,  2.75,  2.75,  2.75,  2.75,  2.75],
       [ 3.  ,  3.  ,  3.  ,  3.  ,  3.  ,  3.  ],
       [ 3.25,  3.25,  3.25,  3.25,  3.25,  3.25],
       [ 3.5 ,  3.5 ,  3.5 ,  3.5 ,  3.5 ,  3.5 ],
       [ 3.75,  3.75,  3.75,  3.75,  3.75,  3.75],
       [ 4.  ,  4.  ,  4.  ,  4.  ,  4.  ,  4.  ],
       [ 4.25,  4.25,  4.25,  4.25,  4.25,  4.25],
       [ 4.5 ,  4.5 ,  4.5 ,  4.5 ,  4.5 ,  4.5 ],
       [ 4.75,  4.75,  4.75,  4

In [30]:
y

array([[0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.

In [31]:
Z = np.sqrt(np.abs(np.cos(x)+np.cos(y)))  # 根据x, y的坐标计算Z值

In [32]:
Z

array([[1.41421356, 1.4031794 , 1.37024909, 1.3159365 , 1.24108916,
        1.14687504],
       [1.4031794 , 1.39205777, 1.35885797, 1.30407105, 1.22850101,
        1.13324083],
       [1.37024909, 1.35885797, 1.32482645, 1.26857063, 1.19074971,
        1.09220187],
       [1.3159365 , 1.30407105, 1.26857063, 1.20970151, 1.12782586,
        1.02323567],
       [1.24108916, 1.22850101, 1.19074971, 1.12782586, 1.03952134,
        0.92499982],
       [1.14687504, 1.13324083, 1.09220187, 1.02323567, 0.92499982,
        0.79413143],
       [1.03476432, 1.0196321 , 0.97381711, 0.89578238, 0.78169016,
        0.62133692],
       [0.90650645, 0.88919422, 0.83626342, 0.74393737, 0.6017111 ,
        0.37023818],
       [0.76410285, 0.74348207, 0.6792906 , 0.56173128, 0.35235702,
        0.3175287 ],
       [0.60977568, 0.58372836, 0.49940859, 0.32173785, 0.29643096,
        0.55933108],
       [0.44593316, 0.40959591, 0.27647594, 0.26354268, 0.51072626,
        0.69700879],
       [0.27513201, 0

# 11 Numpy的where()函数和统计函数 

## 11.1 where()函数

where()函数的语法是 where(condition, [x, y])。

In [33]:
a = np.arange(5)

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
b = np.arange(5, 10)

In [36]:
b

array([5, 6, 7, 8, 9])

In [37]:
c = np.array([True, False, True, False, True])

In [38]:
c

array([ True, False,  True, False,  True])

In [39]:
d = np.empty(5)

In [40]:
d

array([6.95332845e-310, 2.12199579e-314, 3.16202013e-322, 0.00000000e+000,
       0.00000000e+000])

In [41]:
# 使用where条件(bool元素为True时，选择a, 否则选择b)
np.where(c, a, b)

array([0, 6, 2, 8, 4])

In [42]:
a = np.array([[2, -1], [-1, 2]])

In [43]:
a

array([[ 2, -1],
       [-1,  2]])

In [44]:
np.where(a > 0, 1, 0)

array([[1, 0],
       [0, 1]])

# 11.2 统计函数 

In [45]:
a = np.arange(9).reshape(3, 3)

In [46]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
a.sum()

36

In [48]:
a.sum(axis = 0)  # 纵轴

array([ 9, 12, 15])

In [49]:
# 计算数组元素的平均值
a.mean()

4.0

In [50]:
a.mean(0)  # 纵轴

array([3., 4., 5.])

In [51]:
a.min(), a.min(0)

(0, array([0, 1, 2]))

In [52]:
a.max(), a.max(0)

(8, array([6, 7, 8]))

In [53]:
# 计算数组元素的标准差和方差
a.std(), a.var()

(2.581988897471611, 6.666666666666667)

In [54]:
# argmin、 argmax计算最小、最大元素的索引。
a.argmin(), a.argmax()

(0, 8)

In [55]:
# 计算元素的累加和
a.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

# 12 输入与输出

## 12.1 二进制文件 

`load()`, `save()`, `savez()`, `savez_compressed()`

In [56]:
a = np.arange(16).reshape(4, 4)

In [57]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
np.save("./temp_array", a)  #二进制文件

In [59]:
np.load("./temp_array.npy")

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 12.2 文本文件

`savetxt`、`loadtxt()`

In [60]:
a = np.arange(16).reshape(4,4)

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.savetxt("out.txt", a, delimiter=",", fmt="%d")

In [63]:
np.loadtxt("out.txt", delimiter=",")

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])