In [1]:
import numpy as np

In [2]:
a = np.arange(1, 3, 0.5)

In [3]:
a.dtype

dtype('float64')

In [4]:
b = a.astype("int64")

In [5]:
a

array([1. , 1.5, 2. , 2.5])

In [6]:
b

array([1, 1, 2, 2])

In [7]:
b = np.arange(0, 20, 2)

In [8]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
b[2]

4

In [10]:
b[:4]

array([0, 2, 4, 6])

In [11]:
b[:5]

array([0, 2, 4, 6, 8])

In [12]:
b[:4:2]

array([0, 4])

In [13]:
a = np.array(([1,2,3],[4,5,6]))

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[1]

array([4, 5, 6])

In [16]:
a = np.arange(16).reshape(4, 4)

In [17]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
a[0][0]

0

In [19]:
old = a[0].copy()

In [20]:
a[0] = 10

In [21]:
a[0] = old

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a[0:, 1]

array([ 1,  5,  9, 13])

In [24]:
a[1, 0:]

array([4, 5, 6, 7])

# 4 高级索引

**注意：** 与常规索引不同的是，高级索引会复制原数据，并返回一个新的数组。

## 4.1 整数索引

对于一维数组而言，使用数组进行索引，返回的结果和索引数组的形状一样，不同的地方在于被索引数组的相关值会替换索引数组对应位置的值。

In [25]:
a = np.arange(1, 11)

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
a[np.array([[1, 2], [3, 4]])]

array([[2, 3],
       [4, 5]])



现有一个4 x 4的二维数组，需要取出对角线上的元素。

In [28]:
a = np.arange(0, 16).reshape(4, 4)

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
a[[0, 1, 2, 3], [0, 1, 2, 3]]

array([ 0,  5, 10, 15])

也可以在索引数组内重新排列各行的行号来定义索引的顺序。

In [31]:
a[[3, 2, 1, 0]]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

也可以使用负值来索引数组

In [32]:
a[[-1, -2, -3, 0]]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

## 4.2 布尔索引

当索引的方式是布尔数组的时候，就会触发布尔索引。

In [33]:
data = np.random.rand(40).reshape(10, 4)

In [34]:
data

array([[0.46170806, 0.92248773, 0.91378027, 0.09527112],
       [0.19788712, 0.41444807, 0.39639536, 0.28309557],
       [0.57435381, 0.92596383, 0.59430357, 0.39722597],
       [0.41837976, 0.55111622, 0.94579174, 0.58872626],
       [0.76916397, 0.71189234, 0.85137707, 0.96583536],
       [0.16338188, 0.4404936 , 0.62025787, 0.20725474],
       [0.09510781, 0.28538124, 0.7154803 , 0.05986617],
       [0.72959065, 0.93209946, 0.03950976, 0.4964201 ],
       [0.69579484, 0.3943746 , 0.49921167, 0.68052163],
       [0.21791872, 0.60446604, 0.69531524, 0.20293275]])

In [35]:
name = np.array(['小明', '小张', '小王', '小李', '小花', '小宋', '小王', '小张', '小王', '小王'])

In [36]:
name

array(['小明', '小张', '小王', '小李', '小花', '小宋', '小王', '小张', '小王', '小王'],
      dtype='<U2')

In [37]:
data[name == '小王']

array([[0.57435381, 0.92596383, 0.59430357, 0.39722597],
       [0.09510781, 0.28538124, 0.7154803 , 0.05986617],
       [0.69579484, 0.3943746 , 0.49921167, 0.68052163],
       [0.21791872, 0.60446604, 0.69531524, 0.20293275]])

In [38]:
name == '小王'

array([False, False,  True, False, False, False,  True, False,  True,
        True])

在布尔索引的同时也可以进行分片操作

In [39]:
data[name=="小王", 1:]

array([[0.92596383, 0.59430357, 0.39722597],
       [0.28538124, 0.7154803 , 0.05986617],
       [0.3943746 , 0.49921167, 0.68052163],
       [0.60446604, 0.69531524, 0.20293275]])

In [40]:
data[name == "小王", 2]

array([0.59430357, 0.7154803 , 0.49921167, 0.69531524])

可以使用逻辑运算符`＆`、`|`、`~` 连接多个表达式。

In [41]:
data[~(name=='小王')]

array([[0.46170806, 0.92248773, 0.91378027, 0.09527112],
       [0.19788712, 0.41444807, 0.39639536, 0.28309557],
       [0.41837976, 0.55111622, 0.94579174, 0.58872626],
       [0.76916397, 0.71189234, 0.85137707, 0.96583536],
       [0.16338188, 0.4404936 , 0.62025787, 0.20725474],
       [0.72959065, 0.93209946, 0.03950976, 0.4964201 ]])

## 4.3 布尔索引简单的应用

In [42]:
x = np.array([[1, 2], [np.nan, 3], [np.nan, np.nan]])

In [43]:
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [44]:
x[~np.isnan(x)]

array([1., 2., 3.])

In [45]:
x = np.array([1, -1, -2, 3])

In [46]:
x[x < 0] += 20

In [47]:
x

array([ 1, 19, 18,  3])

# 5 改变数组的形状

In [48]:
a = np.arange(24)

In [49]:
a.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

如果reshape()函数中，某个方向上的大小设置为-1，则自动会根据其他方向上设定的大小来计算这个-1方向上的大小。 

In [50]:
a.reshape(2, 3, -1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

**转置**

In [51]:
a = np.arange(24).reshape(2, 4, 3)

In [52]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

np中的数组，可以使用 transpose()函数来进行重新排列。通过-排列各个轴的轴号，来改变数组的结构。“”

In [53]:
a.transpose((2, 1, 0))

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [54]:
np.arange(12).reshape((3, 4)).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

可以使用`ravel()`函数改变数组的形状，它会逐行的读取元素并返回一个一维数组。

In [55]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [56]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

还可以使用`resize()`函数改变数组的形状，与`reshape()`函数不同的是，它将直接在原数组进行修改。

In [58]:
a = np.arange(12).reshape((3, 4))

In [59]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a.resize((6, 2))  # 不返回值，直接在a上更改

In [61]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# 6 组装、分割数组

可以把位于不同方向上的几个数组组装起来。比如一个二维数组，可以在垂直方向上把它们组装起来。

In [62]:
a = np.random.rand(2, 2)

In [63]:
a

array([[0.97105758, 0.11108644],
       [0.20834976, 0.30900044]])

In [64]:
b = np.random.rand(2, 2)

In [65]:
b

array([[0.22025939, 0.68610663],
       [0.74630369, 0.30176438]])

In [66]:
np.vstack((a, b))

array([[0.97105758, 0.11108644],
       [0.20834976, 0.30900044],
       [0.22025939, 0.68610663],
       [0.74630369, 0.30176438]])

可以在横向上把它们组装起来。

In [67]:
np.hstack((a, b))

array([[0.97105758, 0.11108644, 0.22025939, 0.68610663],
       [0.20834976, 0.30900044, 0.74630369, 0.30176438]])

可以对数组进行分割操作。在第2列和第4列对数组进行分割，得到3个数组。得到3个数组，横轴长度分别为2, 2, 4。

In [68]:
a = np.arange(32).reshape(4, 8)

In [69]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [70]:
np.hsplit(a, [2, 4])

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]), array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]), array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]