In [11]:
import numpy as np

In [15]:
a = np.arange(1, 3, 0.5)

In [16]:
a.dtype

dtype('float64')

In [19]:
b = a.astype("int64")

In [20]:
a

array([1. , 1.5, 2. , 2.5])

In [21]:
b

array([1, 1, 2, 2])

In [22]:
b = np.arange(0, 20, 2)

In [24]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
b[2]

4

In [26]:
b[:4]

array([0, 2, 4, 6])

In [28]:
b[:5]

array([0, 2, 4, 6, 8])

In [29]:
b[:4:2]

array([0, 4])

In [30]:
a = np.array(([1,2,3],[4,5,6]))

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a[1]

array([4, 5, 6])

In [38]:
a = np.arange(16).reshape(4, 4)

In [36]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
a[0][0]

0

In [42]:
old = a[0].copy()

In [44]:
a[0] = 10

In [46]:
a[0] = old

In [47]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
a[0:, 1]

array([ 1,  5,  9, 13])

In [49]:
a[1, 0:]

array([4, 5, 6, 7])

# 4 高级索引

**注意：** 与常规索引不同的是，高级索引会复制原数据，并返回一个新的数组。

## 4.1 整数索引

对于一维数组而言，使用数组进行索引，返回的结果和索引数组的形状一样，不同的地方在于被索引数组的相关值会替换索引数组对应位置的值。

In [50]:
a = np.arange(1, 11)

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a[np.array([[1, 2], [3, 4]])]

array([[2, 3],
       [4, 5]])



现有一个4 x 4的二维数组，需要取出对角线上的元素。

In [53]:
a = np.arange(0, 16).reshape(4, 4)

In [54]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
a[[0, 1, 2, 3], [0, 1, 2, 3]]

array([ 0,  5, 10, 15])

也可以在索引数组内重新排列各行的行号来定义索引的顺序。

In [56]:
a[[3, 2, 1, 0]]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

也可以使用负值来索引数组

In [60]:
a[[-1, -2, -3, 0]]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

## 4.2 布尔索引

当索引的方式是布尔数组的时候，就会触发布尔索引。

In [65]:
data = np.random.rand(40).reshape(10, 4)

In [66]:
data

array([[0.99891029, 0.69819839, 0.70275442, 0.50799457],
       [0.24946762, 0.92349475, 0.00944592, 0.71085705],
       [0.09094537, 0.95367289, 0.09276258, 0.23846352],
       [0.22187678, 0.95011661, 0.10776783, 0.37029555],
       [0.97598284, 0.46564569, 0.88075189, 0.06209492],
       [0.5199677 , 0.95448257, 0.05527007, 0.60553176],
       [0.36490626, 0.15422441, 0.71409898, 0.02373928],
       [0.26437997, 0.87915243, 0.3642544 , 0.37664661],
       [0.58217536, 0.73787159, 0.06531745, 0.12642465],
       [0.58592997, 0.994446  , 0.64461702, 0.30229722]])

In [67]:
name = np.array(['小明', '小张', '小王', '小李', '小花', '小宋', '小王', '小张', '小王', '小王'])

In [68]:
name

array(['小明', '小张', '小王', '小李', '小花', '小宋', '小王', '小张', '小王', '小王'],
      dtype='<U2')

In [69]:
data[name == '小王']

array([[0.09094537, 0.95367289, 0.09276258, 0.23846352],
       [0.36490626, 0.15422441, 0.71409898, 0.02373928],
       [0.58217536, 0.73787159, 0.06531745, 0.12642465],
       [0.58592997, 0.994446  , 0.64461702, 0.30229722]])

In [70]:
name == '小王'

array([False, False,  True, False, False, False,  True, False,  True,
        True])

在布尔索引的同时也可以进行分片操作

In [71]:
data[name=="小王", 1:]

array([[0.95367289, 0.09276258, 0.23846352],
       [0.15422441, 0.71409898, 0.02373928],
       [0.73787159, 0.06531745, 0.12642465],
       [0.994446  , 0.64461702, 0.30229722]])

In [72]:
data[name == "小王", 2]

array([0.09276258, 0.71409898, 0.06531745, 0.64461702])

可以使用逻辑运算符`＆`、`|`、`~` 连接多个表达式。

In [73]:
data[~(name=='小王')]

array([[0.99891029, 0.69819839, 0.70275442, 0.50799457],
       [0.24946762, 0.92349475, 0.00944592, 0.71085705],
       [0.22187678, 0.95011661, 0.10776783, 0.37029555],
       [0.97598284, 0.46564569, 0.88075189, 0.06209492],
       [0.5199677 , 0.95448257, 0.05527007, 0.60553176],
       [0.26437997, 0.87915243, 0.3642544 , 0.37664661]])

## 4.3 布尔索引简单的应用

In [74]:
x = np.array([[1, 2], [np.nan, 3], [np.nan, np.nan]])

In [75]:
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [76]:
x[~np.isnan(x)]

array([1., 2., 3.])

In [77]:
x = np.array([1, -1, -2, 3])

In [79]:
x[x < 0] += 20

In [80]:
x

array([ 1, 19, 18,  3])

# 5 改变数组的形状

In [81]:
a = np.arange(24)

In [83]:
a.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

如果reshape()函数中，某个方向上的大小设置为-1，则自动会根据其他方向上设定的大小来计算这个-1方向上的大小。 

In [84]:
a.reshape(2, 3, -1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

**转置**

In [85]:
a = np.arange(24).reshape(2, 4, 3)

In [86]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

np中的数组，可以使用 transpose()函数来进行重新排列。通过-排列各个轴的轴号，来改变数组的结构。“”

In [87]:
a.transpose((2, 1, 0))

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [91]:
np.arange(12).reshape((3, 4)).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

可以使用`ravel()`函数改变数组的形状，它会逐行的读取元素并返回一个一维数组。

In [92]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

还可以使用`resize()`函数改变数组的形状，与`reshape()`函数不同的是，它将直接在原数组进行修改。

In [95]:
a = np.arange(12).reshape((3, 4))

In [96]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a.resize((6, 2))  # 不返回值，直接在a上更改

In [101]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# 6 组装、分割数组